title = "FBO Request"
baseURL = "https://fborequest.github.io"
languageCode = "en-us"
#theme = ["ananke", "matomo"]
theme = ["landing_page", "matomo"]
publishdir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # Used in the footer
  copyright_name = "FBO Request LLC"

  # TODO Enumerate all social icons
  facebook = "https://www.facebook.com/fborequest"
  instagram = "https://www.instagram.com/fborequest/"
  formspree_url = "https://formspree.io/f/mnqooper"

[params.matomo]
url = "https://stats.fborequest.com"
id = 2
host = "stats.fborequest.com"

[[params.feature]]
  icon = "far fa-clock"
  header = "Real time requests"
  text = "Receive aircraft service requests in real time through the web or phone."

[[params.feature]]
  icon = "fas fa-bell"
  header = "Communication"
  text = "Instantly communicate the progress of requests to your customers."

[[params.feature]]
  icon = "fas fa-link"
  header = "Connect"
  text = "Connect customers and employees for a seamless, personalized service."

[[params.feature]]
  icon = "fa fa-users"
  header = "Manage"
  text = "Manage and track your employees workload using data driven analytics."

[[params.feature]]
  icon = "fa fa-tv"
  header = "Display"
  text = "At a glance status for your FBO with our Arrival/Departure Display."

[[params.feature]]
  icon = "fas fa-bolt"
  header = "Streamline"
  text = "Do more with less; enable your FBO to fit the changing needs of the industry."

[[params.header.menu]]
  url = "/"
  title = "Home"

[[params.header.menu]]
  url = "/news"
  title = "News"

[[params.header.menu]]
  url = "/#contact"
  title = "Contact"

